### ISSUE TITLE
playwright brouserのキャッシュ

### ISSUE THREAD

**Issue by s3igo** [s3igo/blog#126]
```yaml
      - name: Install dependencies
        run: npm ci
      - name: Store Playwright's version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright browsers for Playwright's version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx -w app playwright install --with-deps
```
こんなかんじで書いてたけど、ときどきコケるのでやめた
playwrightのオプションで、ブラウザを`node_modules`の中にインストールするのがあったため、それ使えばnode_modulesといっしょにキャッシュできるんか試したい
